export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PRODUCTION_MANAGER: 'PRODUCTION_MANAGER',
  FURNACE_OPERATOR: 'FURNACE_OPERATOR',
  QC_MANAGER: 'QC_MANAGER',
  QC_INSPECTOR: 'QC_INSPECTOR',
  STORE_MANAGER: 'STORE_MANAGER',
  MAINTENANCE_MANAGER: 'MAINTENANCE_MANAGER',
  ACCOUNTS: 'ACCOUNTS',
  CUSTOMER: 'CUSTOMER'
};

export const BATCH_STATUS = {
  PLANNED: 'PLANNED',
  LOADING: 'LOADING',
  HEATING: 'HEATING',
  SOAKING: 'SOAKING',
  QUENCHING: 'QUENCHING',
  TEMPERING: 'TEMPERING',
  COOLING: 'COOLING',
  QC_PENDING: 'QC_PENDING',
  QC_APPROVED: 'QC_APPROVED',
  QC_FAILED: 'QC_FAILED',
  NCR: 'NCR',
  REWORK: 'REWORK',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  COMPLETED: 'COMPLETED'
};

export const FURNACE_STATUS = {
  IDLE: 'IDLE',
  LOADING: 'LOADING',
  HEATING: 'HEATING',
  SOAKING: 'SOAKING',
  QUENCHING: 'QUENCHING',
  TEMPERING: 'TEMPERING',
  COOLING: 'COOLING',
  QC_PENDING: 'QC_PENDING',
  MAINTENANCE: 'MAINTENANCE',
  BREAKDOWN: 'BREAKDOWN'
};

export const JOB_STATUS = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  MATERIAL_PENDING: 'MATERIAL_PENDING',
  READY_FOR_PRODUCTION: 'READY_FOR_PRODUCTION',
  IN_PRODUCTION: 'IN_PRODUCTION',
  QC_PENDING: 'QC_PENDING',
  REWORK: 'REWORK',
  COMPLETED: 'COMPLETED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  CANCELLED: 'CANCELLED'
};

export const STOCK_OWNERSHIP = {
  CUSTOMER: 'CUSTOMER',
  COMPANY: 'COMPANY'
};

export const PROCESS_TYPES = [
  'Carburizing',
  'Hardening & Tempering',
  'Case Hardening',
  'Annealing',
  'Normalizing',
  'Stress Relieving',
  'Carbonitriding',
  'Nitriding',
  'Induction Hardening'
];
